env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
rules: {
  "func-call-spacing": "off",
  "no-unexpected-multiline": "off",
  "semi": [2, "always"],
  "quotes": [2, "double"]
}